
POST http://localhost:8888/user_address HTTP/1.1
Content-Type: "application/json"

{
    "user_id": "7771fe6f-2215-46c0-9a35-56a454bd05fc",
    "cep":"11500260"
}

###

GET http://localhost:8888/user_address/b0ad8f4a-24b5-404a-a919-2add3911939e HTTP/1.1

###

PUT http://localhost:8888/user_address/b0ad8f4a-24b5-404a-a919-2add3911939e HTTP/1.1
Content-Type: "application/json"

{
    "user":{
        "id": "7771fe6f-2215-46c0-9a35-56a454bd05fc"
    },
    "cep":"11500270"
}

###
DELETE http://localhost:8888/user_address/b0ad8f4a-24b5-404a-a919-2add3911939e HTTP/1.1

###

GET http://localhost:8888/user_address/ HTTP/1.1
