version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: userevents
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432

    