// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Event struct {
	ID          string     `json:"id"`
	PerformedAt string     `json:"performedAt"`
	User        *User      `json:"user"`
	EventType   *EventType `json:"eventType"`
}

type EventType struct {
	ID          string   `json:"id"`
	Description string   `json:"description"`
	Events      []*Event `json:"events,omitempty"`
}

type Mutation struct {
}

type NewEvent struct {
	PerformedAt string `json:"performedAt"`
	UserID      string `json:"userId"`
	EventTypeID string `json:"eventTypeId"`
}

type NewEventType struct {
	Description string `json:"description"`
}

type NewUser struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type NewUserAddress struct {
	UserID string `json:"userId"`
	Cep    string `json:"cep"`
}

type OnlyID struct {
	ID string `json:"id"`
}

type Query struct {
}

type User struct {
	ID       string   `json:"id"`
	Name     string   `json:"name"`
	Password string   `json:"password"`
	Email    string   `json:"email"`
	Events   []*Event `json:"events,omitempty"`
}

type UserAddress struct {
	ID   string `json:"id"`
	User *User  `json:"user"`
	Cep  string `json:"cep"`
}
